### ISSUE TITLE
Emote broke table of content align

### ISSUE THREAD

**Issue by nullchilly** [kdheepak/panvimdoc#14]
Thanks for the workflow :)

I have a problem with emote character, it is possible to ignore it?

`README.md`: https://github.com/catppuccin/nvim/blob/afd581cdfa1f50e6d14aea77f50de168fc7296c1/README.md

`Generated vimdoc`: https://github.com/catppuccin/nvim/blob/afd581cdfa1f50e6d14aea77f50de168fc7296c1/doc/catppuccin.txt

`Mis-aligned preview`:

![image](https://user-images.githubusercontent.com/56817415/180178335-c8ed5ae8-3956-4c00-b7d6-9ef0d578fe5e.png)

**Comment by nekowinston** [comment]
Hi there! :wave:

I decided to have a go at adding this feature in [my fork](https://github.com/nekowinston/panvimdoc), by adding [Demojify](https://github.com/buildthomas/Demojify) & a custom lua filter.
I'm happy to open a PR for it, but wouldn't mind if you just implement a similar, cleaner solution instead.

Here's a look at the output it produces, at the moment: https://github.com/nekowinston/doctest/blob/main/doc/catppuccin.txt

**Comment by kdheepak** [comment]
Thanks for taking a stab at this! `demojify` looks like a good idea for this. Would you be willing to submit a PR?

**Comment by nekowinston** [comment]
Absolutely! But I have some concerns with how I "solved" the lua import. I just moved it to `/usr/share/lua/common/Demojify.lua` in the Dockerfile, because I couldn't quite figure out how to solve the `require()` path issue.

I'll open a PR, and we can review if necessary. 👍
