### ISSUE TITLE
Handling of duplicate tags

### ISSUE THREAD

**Issue by smjonas** [kdheepak/panvimdoc#18]
Hey, I'm using panvimdoc for my plugin [snippet-converter.nvim](https://github.com/smjonas/snippet-converter.nvim). Everything works great except that panvimdoc does not handle duplicate tags if there are subsections that occur multiple times in the markdown file.

E.g. I have `## Examples` in sections 3 (`Transforming snippets`) and 4 (`Sorting snippets`). The resulting docs are
```helpdocs
3. Transforming snippets             |snippet-converter-transforming-snippets|
  - Examples                                      |snippet-converter-examples|
4. Sorting snippets                       |snippet-converter-sorting-snippets|
  - Examples                                      |snippet-converter-examples|
```

Would it be possible to change the subsection tags to `snippet-converter-transforming-snippets-examples` and `snippet-converter-sorting-snippets-examples` if duplicate tags are found?

**Comment by kdheepak** [comment]
I've added a `dedupsubheadings` option but I haven't had the chance to test it extensively. It'll currently prepend the heading to all subheadings, and hence it defaults to `false`.

**Comment by kdheepak** [comment]
I'll comment here if I make changes to the options and if it affects your plugin! For now, I believe it should solve your issue. You can see this commit for what it looks like for me:

https://github.com/kdheepak/panvimdoc/commit/4a11fe9f58789813ca7514253e3da1f381ee9813

**Comment by smjonas** [comment]
Thank you very much for tackling this issue! I will let you know once the `snippet-converter` docs have been regenerated after the next docs update and close the issue in case everything is fine :)

**Comment by kdheepak** [comment]
Great! Thanks for offering to test!

**Comment by smjonas** [comment]
Hey, I have now merged the PR and added `dedupsubheadings = true` to the GitHub action. But unfortunately, the duplicate subheadings still remain. You can see how I tested this by looking at the two most recent commits on the `docs` branch: https://github.com/smjonas/snippet-converter.nvim/commits/docs. Any idea what I might be doing wrong?
