### ISSUE TITLE
Highlight code blocks in treesitter 

### ISSUE THREAD

**Issue by nullchilly** [kdheepak/panvimdoc#20]
https://github.com/neovim/neovim/pull/21154

[PSA: Code Blocks can now be highlighted in vimdoc](https://www.reddit.com/r/neovim/comments/z2gid9/psa_code_blocks_can_now_be_highlighted_in_vimdoc/)

Preferably add an option called `treesitter = true`

```lua
>lua
-- This code will be highlighted as lua
<
```

Preview

![image](https://user-images.githubusercontent.com/56817415/203695561-3d5c1155-ae91-43d4-a19b-d5b8718779b0.png)

**Comment by folke** [comment]
You can add the code below to your github workflow to replace any code block with a lua code block:

```yaml
- name: Code Blocks
  run: sed -i 's/^>$/>lua/' doc/your_plugin.nvim.txt
```

**Comment by kdheepak** [comment]
Thanks for opening the issue and bringing this feature to my attention. I should add this as a feature directly but haven’t gotten around to it. 

I’ve been dealing with some stuff in my personal life and my time on open source projects has taken a hit. But I can review and merge a PR if required!

**Comment by folke** [comment]
No hurry. The work-around works perfectly fine for me for now :)

**Comment by kdheepak** [comment]
Thanks for bringing this to my attention! Adding `treesitter: true` will result in codeblocks with the language in vimdoc.

See this commit for an example of how to use it: https://github.com/kdheepak/panvimdoc/commit/0c1c4e1edd0b54ac2f459fbe7af8e57db7118045

And see this commit for an example of what the vimdoc output is with that option enabled: https://github.com/kdheepak/panvimdoc/commit/460adc9085639d110ef7b9dbb783e404596fe956

**Comment by folke** [comment]
Thanks!

**Comment by nullchilly** [comment]
https://github.com/catppuccin/nvim/commit/ee756bf71c444303d9ea378dc4996e59edb1aa2b Works 🥳
