### ISSUE TITLE
Strange handling of level 4 headings

### ISSUE THREAD

**Issue by ramojus** [kdheepak/panvimdoc#22]
this markdown

```markdown
### Color set specific config options
#### Mellifluous
default config:
```

in vimdoc looks like this:

![image](https://user-images.githubusercontent.com/41536253/209701960-8e3a9b74-cb05-47a5-9260-2fd85aa3acf1.png)

I think level 4 headings should be converted in the same style as level 3 headings or level 5 headings:
```diff
diff --git a/scripts/panvimdoc.lua b/scripts/panvimdoc.lua
index 69dfaa3..6dfd726 100644
--- a/scripts/panvimdoc.lua
+++ b/scripts/panvimdoc.lua
@@ -375,19 +375,9 @@ function Header(lev, s, attr)
     return left .. " ~"
   end
   if lev == 4 then
-    left = ""
-    current_element = s
-    right = string.gsub(s, "{.+}", "")
-    right = string.gsub(right, "%[.+%]", "")
-    right = string.gsub(right, "^%s*(.-)%s*$", "%1")
-    right = string.gsub(right, "%s", "-")
-    right = string.format("*%s-%s*", stringify(meta.project), right)
-    if attr.doc then
-      right = right .. " *" .. attr.doc .. "*"
-    end
-    padding = string.rep(" ", 78 - #left - #right)
-    local r = string.format("%s%s%s", left, padding, right)
-    return r
+    left = string.upper(s)
+    current_element = nil
+    return left -- .. " ~"?
   end
   if lev >= 5 then
     left = string.upper(s)
```

**Comment by kdheepak** [comment]
Hey! Thanks for the PR!

Why do you think level 4 should be made into the same as level 5?

level 4 headings right now serve as tags that you can reference from anywhere in the vim doc. Have you used this feature?

And I’m sure a few people depend on this already, so I don’t think we should merge this unless there’s a very good reason to break backwards compatibility. 

What do you think?

**Comment by ramojus** [comment]
Hey!

I haven't thought about backwards compatibility, that's a good point. Just seems like a very odd choice to handle level 4 headings this way. I think tags are awesome for level 1 and 2 headings, but not level 4, especially when there are no tags for level 3 headings.

Maybe we could do it as an option then? I'm thinking `level4headingstags: true`, with `true` as the default value. I would update the PR.

**Comment by kdheepak** [comment]
Level 3 is "special" for documentation purposes and that's why it was excluded. I'm open to have an option for level 4 headings though.

**Comment by kdheepak** [comment]
My previous comment here was incorrect. Level 4 headings are the ones that are special. They are used for mappings. See this section of the documentation: https://github.com/kdheepak/panvimdoc/blob/542eb202d2f444dde5004fe27d9a90a50be6866c/doc/panvimdoc.md#mappings

For example, this:

```md
#### pv{motion}

Command that operates over {motion} moved.
pvd

Command that takes [count] lines.

#### :[range]CommandName {doc=CommandName}

Command that operates over [range].

#### {Visual}pv

Command that operates over highlighted lines.
```

becomes this:

```

                                                                *panvimdoc-pv*

pv{motion}                             Command that operates over {motion}
                                       moved.


                                                               *panvimdoc-pvd*

pvd                                    Command that takes [count] lines.


                                        *panvimdoc-:CommandName* *CommandName*

:[range]CommandName                    Command that operates over [range].


                                                                *panvimdoc-pv*

{Visual}pv                             Command that operates over highlighted
                                       lines.
```

The reason this is like this is that if you have vim or nvim commands that you want to document, you can do so as level 4 headings.

But this is co-opting markdown syntax into something that it isn't, so I'll add it behind a flag that defaults to `false` and has to be enabled to be `true`. That would be a breaking change though unfortunately but it'll make level 4 behave the same way as level 5 headers.

**Comment by ramojus** [comment]
That's an interesting feature, I get it now, thanks!

**Comment by kdheepak** [comment]
This is an example of the type of docs that you might want to generate for command mappings:

```

COMMANDS                                        *fugitive-commands*

These commands are local to the buffers in which they work (generally, buffers
that are part of Git repositories).

                                                *fugitive-:G*
:G [args]               Same as :Git, but two characters shorter.

                                                *:Git*
:Git {args}             Run an arbitrary git command and display any output.
                        On UNIX this uses a pty and on other platforms it uses
                        a pipe, which will cause some behavior differences
                        such as the absence of progress bars.  Any file the
                        command edits (for example, a commit message) will be
                        loaded into a split window.  Closing that window will
                        resume running the command.  A few Git subcommands
                        have different behavior; these are documented below.

                                                *:Git!*
:Git! {args}            Run an arbitrary git command in the background and
                        stream the output to the preview window.  Requires a
                        Vim with |setbufline()|.  Press CTRL-D during an
                        interactive :Git invocation to switch to this mode
                        retroactively.

                                                *:Git_--paginate* *:Git_-p*
```

taken from the very well documented vim-fugitive: https://github.com/tpope/vim-fugitive/blob/99cdb88bc64063dc4656ae53496f06fb2a394cd4/doc/fugitive.txt#L13-L37

But right now it appears people just type this in a vimdoc codeblock directly and manually format it. So it appears that no one is using it?

**Comment by kdheepak** [comment]
I've removed this feature in the next version of the package. It'll make it easier for people to use. If I reintroduce this feature, it'll be with an alternative syntax.
