### ISSUE TITLE
[Enhancement] Strip GitHub emojis

### ISSUE THREAD

**Issue by olimorris** [kdheepak/panvimdoc#26]
I use GitHub emoji's in my `README.md` and they are defined between `:`'s. For example:

- `:rainbow:` = :rainbow:
- `:wrench:` = :wrench:
- `:camera_flash:` = :camera_flash:

It would be great to be able to have the option to strip these out.

**Comment by olimorris** [comment]
Nope, hence the enhancement. The [demojify](https://github.com/kdheepak/panvimdoc/blob/main/lib/Demojify.lua) library looks for emoji's rather than strings between two colons like GitHub emoji's

**Comment by gennaro-tedesco** [comment]
I see, thank you for clarifying!

**Comment by kdheepak** [comment]
Do we want to strip them out or convert them to their emoji in the vimdoc file? I think the latter would be nicer, right?

**Comment by olimorris** [comment]
If I call `demojify: true` I would probably expect all emoji's to be removed

**Comment by olimorris** [comment]
One thing I've noticed with this is that in table of contents, github emoji's are replaced with `nil`:

### Generated docs
<img width="770" alt="Screen Shot 2023-02-22 at 15 12 19@2x" src="https://user-images.githubusercontent.com/9512444/220665287-5a4aace3-cc61-4c45-a298-2d41027e5f44.png">

### Original Readme
<img width="905" alt="Screen Shot 2023-02-22 at 15 14 07@2x" src="https://user-images.githubusercontent.com/9512444/220665510-f38402e3-a728-495b-a1df-faf71e8a1c14.png">

**Comment by kdheepak** [comment]
@olimorris this should be fixed now. I added a test based on your readme too: https://github.com/kdheepak/panvimdoc/blob/34da4138f2589fd2f230a05066b913aadea55fe5/test/toc-emojis.jl
