### ISSUE TITLE
remove `html` elements from parsed text

### ISSUE THREAD

**Issue by gennaro-tedesco** [kdheepak/panvimdoc#28]
Thank you for the great work!

## Description

Would it be possible to strip the html block elements from the README instead of parsing them into the generated doc file? Very often the README contains images, screencasts or general html blocks for divisions and alignment of graphical content that are irrelevant in a text file.

## Example 
```
this is my great software, and this is a demo of it

<h2 align="center">
  <img alt="bla" src="blabla"/>
</h2>
```
should be parsing the text only and skip the `<...>` tags content (whether it is reasonable to leave pending text without explanation in a doc file is another matter, and can be left to the user to decide whether or not to strip the html blocks off).

**Comment by kdheepak** [comment]
Thanks for opening an issue. I think this is a good idea, especially because pandoc supports div blocks using the triple colon syntax.

**Comment by gennaro-tedesco** [comment]
Thank you for your prompt work! Must one use `kdheepak/panvimdoc@v3` as per [docs](https://github.com/kdheepak/panvimdoc#using-github-actions)? This however excepts with 
```
Error: Unable to resolve action `kdheepak/panvimdoc@v3`, unable to find version `v3`
```
I guess fully specifying version `@v3.0.3` or `@main` would still work?

**Comment by kdheepak** [comment]
Weird, I thought that worked.

> I guess fully specifying version @v3.0.3 or @main would still work?

yes, you can definitely use `@main` which is what I've been doing in other projects.

**Comment by kdheepak** [comment]
It looks like other projects that use github actions delete the `v3` tag and re-tag it every time there's a minor or patch version update. There's very little I expect to break in this package, so I'm just going to ask users to either pin the exact version or stick to `@main` and risk dealing with something I mess up every once in a while :)

**Comment by gennaro-tedesco** [comment]
I have re-run the actions and all works fine!! :)
