### ISSUE TITLE
Multiple markdown files

### ISSUE THREAD

**Issue by chipsenkbeil** [kdheepak/panvimdoc#41]
There's mention in the readme about support for multiple markdown files, but I can't figure out how that would work. Do you provide a list of files to the `pandoc` field and it merges them into a single vimdoc file? Or will it generate a vimdoc file per markdown file?

**Comment by kdheepak** [comment]
If you include any markdown file it’ll generate one vimdoc file. 

This is an example of how to include other markdown files. 

````markdown
Markdown content here. 

```{.include}
README.md
```

More markdown content here. 
````

You can run the script individually on different Markdown files if you want to generate separate vimdoc files.

**Comment by chipsenkbeil** [comment]
Ah, just found that section in your docs! Thanks!

**Comment by kdheepak** [comment]
Great! Glad that works for you!
